import "./globals.css";
import { Rubik } from "next/font/google";
import ProviderConfig from "@/redux/provider/ProviderConfig";
;

const rubik = Rubik({ subsets: ["hebrew"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProviderConfig>
      <html lang="en">
        <body className={rubik.className}>
          {children}
        </body>
      </html>
    </ProviderConfig>
  );
}
